# Generated by Django 5.1.15 on 2026-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('specialist', 'Специалист'), ('admin', 'Администратор')], default='parent', max_length=20, verbose_name='Роль'),
        ),
    ]
