# Generated by Django 5.1.15 on 2026-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст (в месяцах)'),
        ),
    ]
