# Generated by Django 5.1.15 on 2026-03-15 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_age_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=120, verbose_name='Имя ребёнка')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Пол')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('filled_by', models.CharField(blank=True, choices=[('mother', 'мать'), ('father', 'отец'), ('grandmother', 'бабушка'), ('other_family', 'другой член семьи'), ('nanny', 'няня / воспитатель')], max_length=20, verbose_name='Кто заполняет')),
                ('birth_week', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Неделя рождения')),
                ('birth_conditions', models.CharField(blank=True, choices=[('normal', 'нормальные'), ('child_complications', 'осложнения для ребенка'), ('mother_complications', 'осложнения для матери'), ('both_complications', 'осложнения для обоих')], max_length=30, verbose_name='Условия рождения')),
                ('child_health', models.CharField(blank=True, choices=[('healthy', 'здоров'), ('recovered', 'полностью выздоровел после тяжелой болезни'), ('weakened', 'ослаблен после тяжелой болезни'), ('ill', 'физически болен')], max_length=20, verbose_name='Состояние здоровья')),
                ('seizures', models.BooleanField(default=False, verbose_name='Судороги')),
                ('where_child_grows', models.CharField(blank=True, choices=[('family', 'в семье'), ('family_nursery', 'в семье и яслях/садике'), ('nursery_24', 'в круглосуточных яслях'), ('orphanage', 'в детском доме')], max_length=20, verbose_name='Где растёт ребёнок')),
                ('family_language', models.CharField(blank=True, choices=[('russian_only', 'только русский'), ('russian_other', 'русский и другой')], max_length=20, verbose_name='Язык в семье')),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество детей в семье')),
                ('main_caregiver', models.CharField(blank=True, choices=[('mother', 'мать'), ('father', 'отец'), ('grandmother', 'бабушка'), ('other_family', 'другой член семьи'), ('nanny', 'няня / воспитатель')], max_length=20, verbose_name='Основной уход')),
                ('caregiver_mood', models.CharField(blank=True, choices=[('cheerful', 'бодрое'), ('calm', 'спокойное'), ('irritated', 'раздраженное'), ('depressed', 'подавленное')], max_length=20, verbose_name='Настроение ухаживающего')),
                ('caregiver_values', models.CharField(blank=True, choices=[('obedience', 'послушание'), ('sociability', 'общительность'), ('curiosity', 'любопытство')], max_length=20, verbose_name='Ценности ухаживающего')),
                ('economic_status', models.CharField(blank=True, choices=[('good', 'хорошее'), ('average', 'среднее'), ('poor', 'плохое'), ('very_poor', 'очень плохое')], max_length=20, verbose_name='Материальное положение')),
                ('mother_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст матери')),
                ('father_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст отца')),
                ('caregiver_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст ухаживающего')),
                ('mother_education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'неполное среднее'), (2, 'среднее'), (3, 'среднее специальное'), (4, 'неполное высшее'), (5, 'высшее')], null=True, verbose_name='Образование матери')),
                ('father_education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'неполное среднее'), (2, 'среднее'), (3, 'среднее специальное'), (4, 'неполное высшее'), (5, 'высшее')], null=True, verbose_name='Образование отца')),
                ('caregiver_education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'неполное среднее'), (2, 'среднее'), (3, 'среднее специальное'), (4, 'неполное высшее'), (5, 'высшее')], null=True, verbose_name='Образование ухаживающего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета ребёнка',
                'verbose_name_plural': 'Анкеты детей',
                'ordering': ['-created_at'],
            },
        ),
    ]
