# Generated by Django 5.1.15 on 2026-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='age_max_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='age_min_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
