# Generated by Django 5.1.15 on 2026-03-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_age_months'),
        ('surveys', '0002_question_age_max_months_question_age_min_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_sessions', to='children.child'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='consent_to_send',
            field=models.BooleanField(default=False, verbose_name='Согласие на отправку специалисту'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='final_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Итоговый балл'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='result_text',
            field=models.TextField(blank=True, verbose_name='Заключение'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SpecialistNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('recommendation', models.TextField(blank=True, verbose_name='Рекомендация для родителей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_notes', to=settings.AUTH_USER_MODEL)),
                ('survey_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='surveys.surveysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
