# Generated by Django 5.1.15 on 2026-03-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveysession_child_surveysession_consent_to_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidNorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.PositiveSmallIntegerField(unique=True, verbose_name='Возраст (месяцев)')),
                ('normal_score', models.PositiveIntegerField(verbose_name='Норма (мин. балл)')),
                ('mild_delay_score', models.PositiveIntegerField(verbose_name='Порог лёгкого отставания')),
            ],
            options={
                'verbose_name': 'Норма KID',
                'verbose_name_plural': 'Нормы KID',
                'ordering': ['age_months'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='child_age_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст ребёнка (месяцев)'),
        ),
        migrations.CreateModel(
            name='SurveyScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение (1, 2, 3)')),
                ('text', models.CharField(max_length=200)),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Балл')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_options', to='surveys.surveytype')),
            ],
            options={
                'ordering': ['survey_type', 'value'],
                'unique_together': {('survey_type', 'value')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_scale_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyscaleoption'),
        ),
    ]
