# Generated by Django 5.1.15 on 2026-03-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_profile_anketa'),
        ('surveys', '0005_seed_kid_rcdi_scale_and_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='child_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_sessions', to='children.childprofile'),
        ),
    ]
