# Generated by Django 5.1.15 on 2026-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_session_child_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.FloatField(verbose_name='Возраст (месяцев)')),
                ('category', models.CharField(db_index=True, max_length=10, verbose_name='Категория')),
                ('normal', models.FloatField(verbose_name='Норма (порог)')),
                ('warning', models.FloatField(verbose_name='Пограничное (порог)')),
                ('low', models.FloatField(verbose_name='Низкий уровень (порог)')),
            ],
            options={
                'verbose_name': 'Норма KID (по категории)',
                'verbose_name_plural': 'Нормы KID (по категориям)',
                'ordering': ['age_months', 'category'],
            },
        ),
        migrations.CreateModel(
            name='RCDINorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.FloatField(verbose_name='Возраст (месяцев)')),
                ('sex', models.CharField(choices=[('M', 'М'), ('F', 'Ж')], db_index=True, max_length=1)),
                ('category', models.CharField(db_index=True, max_length=10, verbose_name='Категория')),
                ('normal', models.FloatField(verbose_name='Норма (порог)')),
                ('warning', models.FloatField(verbose_name='Пограничное (порог)')),
                ('low', models.FloatField(verbose_name='Низкий уровень (порог)')),
            ],
            options={
                'verbose_name': 'Норма RCDI',
                'verbose_name_plural': 'Нормы RCDI',
                'ordering': ['age_months', 'sex', 'category'],
            },
        ),
        migrations.DeleteModel(
            name='KidNorms',
        ),
        migrations.RenameField(
            model_name='surveysession',
            old_name='final_score',
            new_name='total_score',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='per_category_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='Баллы по категориям'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='per_category_status',
            field=models.JSONField(blank=True, null=True, verbose_name='Оценка по категориям'),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='child_age_months',
            field=models.FloatField(blank=True, null=True, verbose_name='Возраст ребёнка (месяцев)'),
        ),
        migrations.AddIndex(
            model_name='kidnorm',
            index=models.Index(fields=['category', 'age_months'], name='surveys_kid_categor_dbd04a_idx'),
        ),
        migrations.AddIndex(
            model_name='rcdinorm',
            index=models.Index(fields=['sex', 'category', 'age_months'], name='surveys_rcd_sex_464abd_idx'),
        ),
    ]
