# Generated by Django 5.1.15 on 2026-03-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_category_scoring_kid_rcdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysession',
            name='total_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Общий балл'),
        ),
    ]
