# Generated by Django 5.1.15 on 2026-03-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_total_score_tweak'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, null=True, verbose_name='Уровень риска'),
        ),
    ]
