# Generated by Django 5.1.15 on 2026-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_mchat_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='guest_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения (гость)'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='guest_child_profile_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Анкета ребёнка (гость)'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='guest_contact_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Контакты (гость)'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='guest_gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол (гость)'),
        ),
    ]
