# Generated by Django 5.1.15 on 2026-04-21 20:36

from django.db import migrations, models


def _existing_surveysession_columns(schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute("PRAGMA table_info(surveys_surveysession)")
            return {row[1] for row in cursor.fetchall()}
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'surveys_surveysession'
                """
            )
            return {row[0] for row in cursor.fetchall()}
    return set()


def ensure_ejs_surveysession_columns(apps, schema_editor):
    """
    Add ЕЖС-related SurveySession columns only if missing.

    Local SQLite may already have these columns (created outside this migration
    history); fresh PostgreSQL on Render does not. This keeps `migrate` safe on both.
    """
    existing = _existing_surveysession_columns(schema_editor)
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if "ejs_routine_analysis" not in existing:
            if connection.vendor == "postgresql":
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN IF NOT EXISTS ejs_routine_analysis jsonb NULL"
                )
            else:
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN ejs_routine_analysis TEXT NULL"
                )

        if "problematic_routines_count" not in existing:
            if connection.vendor == "postgresql":
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN IF NOT EXISTS problematic_routines_count smallint NULL"
                )
            else:
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN problematic_routines_count integer NULL"
                )

        if "recommended_specialist_consultation" not in existing:
            if connection.vendor == "postgresql":
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN IF NOT EXISTS recommended_specialist_consultation "
                    "boolean NOT NULL DEFAULT false"
                )
            else:
                cursor.execute(
                    "ALTER TABLE surveys_surveysession "
                    "ADD COLUMN recommended_specialist_consultation integer NOT NULL DEFAULT 0"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_surveysession_ejs_routine_analysis_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_ejs_surveysession_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="surveysession",
                    name="ejs_routine_analysis",
                    field=models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="ЕЖС: анализ по рутинам",
                    ),
                ),
                migrations.AddField(
                    model_name="surveysession",
                    name="problematic_routines_count",
                    field=models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ЕЖС: проблемных рутин",
                    ),
                ),
                migrations.AddField(
                    model_name="surveysession",
                    name="recommended_specialist_consultation",
                    field=models.BooleanField(
                        default=False,
                        verbose_name="ЕЖС: рекомендована консультация специалиста",
                    ),
                ),
            ],
        ),
    ]
